project_id = "zewszfgmysyocroavlja"

[functions.send-group-email]
verify_jwt = false

[functions.meeting-reminders]
verify_jwt = false

[functions.send-satisfaction-survey]
verify_jwt = false

[functions.task-automation]
verify_jwt = false

[functions.timesheet-reminder]
verify_jwt = false

[functions.budget-monitor]
verify_jwt = false
